# Generated by Django 4.2.13 on 2024-07-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_rename_cordinates_farm_coordinates'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='farms',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='farms',
            field=models.ManyToManyField(to='farms.farm'),
        ),
    ]
