# Generated by Django 4.2.13 on 2024-07-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_alter_farm_name'),
        ('users', '0003_alter_userprofile_email_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='farms',
            field=models.ManyToManyField(blank=True, null=True, to='farms.farm'),
        ),
    ]
