databases:
  - name: dairydrivedb
    plan: free
    databaseName: dairydrive
    user: dairydrive

services:
  - type: web
    plan: free
    name: dairydrive
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn dairydrive.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dairydrivedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4