# Generated by Django 4.2.13 on 2024-07-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaltype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
