# Generated by Django 4.2.13 on 2024-07-24 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_farm_code'),
        ('animals', '0004_animal_gender_animal_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalbreed',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farms.farm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animaltype',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farms.farm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animalbreed',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
