# Generated by Django 4.2.13 on 2025-03-31 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0006_farm_image_farm_image_refference'),
        ('animals', '0005_animalbreed_farm_animaltype_farm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtificialInsemination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semen_code', models.CharField(max_length=100)),
                ('insemination_date', models.DateField()),
                ('technician', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('SUCCESSFUL', 'Successful'), ('UNSUCCESSFUL', 'Unsuccessful'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_records', to='animals.animal')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animalbreed')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='ai_sire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_ai', to='animals.artificialinsemination'),
        ),
    ]
