# Generated by Django 4.2.13 on 2025-06-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_artificialinsemination_animal_ai_sire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date_of_death',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
