# Generated by Django 4.2.13 on 2024-10-15 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_animalbreed_farm_animaltype_farm_and_more'),
        ('feeds', '0002_animalfeedtype_farm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalfeedentry',
            name='animal',
        ),
        migrations.AddField(
            model_name='animalfeedentry',
            name='animal_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='animals.animaltype'),
            preserve_default=False,
        ),
    ]
