# Generated by Django 4.2.13 on 2025-02-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_animalfeedtype_created_at_animalfeedtype_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalfeedentry',
            name='feed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animalfeedentry',
            name='feed_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
