# Generated by Django 4.2.13 on 2025-02-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_animalfeedentry_feed_date_animalfeedentry_feed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalfeedentry',
            name='cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='animalfeedentry',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
