# Generated by Django 4.2.13 on 2025-02-11 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_farm_image_farm_image_refference'),
        ('feeds', '0007_animalfeedentry_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalfeedentry',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farms.farm'),
            preserve_default=False,
        ),
    ]
