# Generated by Django 4.2.13 on 2025-05-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_animalfeedpurchase_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalfeedpurchase',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animalfeedpurchase',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
