# Generated by Django 4.2.13 on 2025-06-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0007_transaction_expense_equipment'),
        ('feeds', '0010_alter_animalfeedpurchase_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalfeedpurchase',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animalfeedpurchase',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='feed_purchases', to='farms.transaction'),
        ),
    ]
