# Generated by Django 4.2.13 on 2025-07-09 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0008_alter_transaction_transaction_code'),
        ('feeds', '0011_animalfeedpurchase_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalfeedpurchase',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='animalfeedpurchase',
            name='transactions',
            field=models.ManyToManyField(blank=True, null=True, related_name='feed_purchases', to='farms.transaction'),
        ),
    ]
