# Generated by Django 4.2.13 on 2025-07-09 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_animalfeedpurchase_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalfeedpurchase',
            name='transactions',
        ),
    ]
