# Generated by Django 4.2.13 on 2024-07-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='cordinates',
            new_name='coordinates',
        ),
    ]
