# Generated by Django 4.2.13 on 2024-07-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_alter_farm_coordinates_alter_farm_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
