# Generated by Django 4.2.13 on 2024-07-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_alter_farm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
