# Generated by Django 4.2.13 on 2024-07-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_farm_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='image_refference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
