# Generated by Django 4.2.13 on 2025-06-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0007_transaction_expense_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
