# Generated by Django 4.2.13 on 2025-07-22 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0010_add_expense_category_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='transactions',
        ),
    ]
