# Generated by Django 4.2.13 on 2025-07-25 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0011_remove_expense_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='max_users',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
