# Generated by Django 4.2.13 on 2025-03-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='image_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
