# Generated by Django 4.2.13 on 2025-05-13 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_healthrecord_image_healthrecord_image_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='total_cost',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='unit_cost',
        ),
    ]
