# Generated by Django 4.2.13 on 2025-06-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0008_alter_transaction_transaction_code'),
        ('health', '0003_rename_total_cost_treatment_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatment',
            name='transactions',
            field=models.ManyToManyField(blank=True, null=True, related_name='treatment', to='farms.transaction'),
        ),
    ]
