# Generated by Django 4.2.13 on 2025-07-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0008_alter_transaction_transaction_code'),
        ('health', '0004_treatment_is_paid_treatment_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='treatment', to='farms.transaction'),
        ),
    ]
