# Generated by Django 4.2.13 on 2025-07-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_sale_quantity_alter_sale_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
